root_folders:
  - name: raw
    subfolders:
      - name: identity
        subfolders: []
      - name: organizzazione
        subfolders: []
      - name: artefatti-operativi
        subfolders: []
      - name: glossario
        subfolders: []
      - name: best-practices
        subfolders: []
      - name: normativa
        subfolders: []
      - name: scenario
        subfolders: []
      - name: economy
        subfolders: []
      - name: template-documenti
        subfolders: []
  - name: contrattualistica
    subfolders: []
